/* Unibox — les quais.
 *
 *   #  mur           .  emplacement   $  caisse
 *   *  caisse posée   @  vous          +  vous sur un emplacement
 */

const LEVELS = [
  {
    id: '01-prise-en-main',
    name: "Prise en main",
    hint: "Une caisse, une marque au sol.",
    par: 2,
    map: [
      "#######",
      "#     #",
      "# @$ .#",
      "#     #",
      "#######",
    ].join('\n'),
  },
  {
    id: '02-petit-quai',
    name: "Petit quai",
    hint: "De la place tout autour : profitez-en.",
    par: 5,
    map: [
      "#######",
      "#@   .#",
      "#     #",
      "# $   #",
      "#     #",
      "#######",
    ].join('\n'),
  },
  {
    id: '03-la-reserve',
    name: "La réserve",
    hint: "Quatre murs et rien pour se cacher.",
    par: 7,
    map: [
      "#######",
      "#@$  .#",
      "#   $ #",
      "#.    #",
      "#     #",
      "#######",
    ].join('\n'),
  },
  {
    id: '04-le-pilier',
    name: "Le pilier",
    hint: "Contourner coûte moins cher que forcer.",
    par: 8,
    map: [
      "########",
      "#+     #",
      "#  ##  #",
      "#  ##$ #",
      "# $ .  #",
      "########",
    ].join('\n'),
  },
  {
    id: '05-autour-du-bloc',
    name: "Autour du bloc",
    hint: "Le bloc central sert de butoir.",
    par: 9,
    map: [
      "########",
      "#@     #",
      "#  ##$ #",
      "#  ## $#",
      "#.    .#",
      "########",
    ].join('\n'),
  },
  {
    id: '06-le-croisement',
    name: "Le croisement",
    hint: "Quatre branches, aucune ne va tout droit.",
    par: 11,
    map: [
      "########",
      "##@ . ##",
      "##    ##",
      "#     .#",
      "# $    #",
      "##$   ##",
      "##    ##",
      "########",
    ].join('\n'),
  },
  {
    id: '07-les-angles-coupes',
    name: "Les angles coupés",
    hint: "Les coins mangés rétrécissent les manœuvres.",
    par: 12,
    map: [
      "########",
      "##@   ##",
      "##$   ##",
      "# $    #",
      "#      #",
      "##   .##",
      "##   .##",
      "########",
    ].join('\n'),
  },
  {
    id: '08-deux-allees',
    name: "Deux allées",
    hint: "Par la gauche ou par la droite, mais choisir tôt.",
    par: 10,
    map: [
      "########",
      "#@.  $.#",
      "# $##  #",
      "#  ## $#",
      "#    . #",
      "########",
    ].join('\n'),
  },
  {
    id: '09-retour-de-tournee',
    name: "Retour de tournée",
    hint: "On connaît les lieux ; ça ne suffit pas.",
    par: 12,
    map: [
      "########",
      "#+ . $ #",
      "# $##  #",
      "#  ##$ #",
      "#   .  #",
      "########",
    ].join('\n'),
  },
  {
    id: '10-le-carre',
    name: "Le carré",
    hint: "Ni obstacle ni excuse.",
    par: 13,
    map: [
      "########",
      "#@  ...#",
      "# $    #",
      "# $$   #",
      "#      #",
      "########",
    ].join('\n'),
  },
  {
    id: '11-le-te',
    name: "Le té",
    hint: "Deux couloirs, une seule bonne entrée.",
    par: 14,
    map: [
      "#########",
      "#@    ..#",
      "# $###  #",
      "# $.#   #",
      "# $ #   #",
      "#       #",
      "#########",
    ].join('\n'),
  },
  {
    id: '12-le-muret',
    name: "Le muret",
    hint: "Un mur au milieu, deux façons d'en faire le tour.",
    par: 15,
    map: [
      "#########",
      "#@  . $.#",
      "#       #",
      "# ##### #",
      "# $     #",
      "# $    .#",
      "#########",
    ].join('\n'),
  },
  {
    id: '13-les-ilots',
    name: "Les îlots",
    hint: "Quatre blocs, huit passages, un seul chemin utile.",
    par: 16,
    map: [
      "##########",
      "#@  .  . #",
      "# ##  ## #",
      "# $      #",
      "# ##$ ## #",
      "#.     $ #",
      "##########",
    ].join('\n'),
  },
  {
    id: '14-petit-dedale',
    name: "Petit dédale",
    hint: "Repérer les allées libres avant de pousser.",
    par: 17,
    map: [
      "##########",
      "#@     . #",
      "# ##  ## #",
      "# $      #",
      "# ##$ ##.#",
      "#  .   $ #",
      "##########",
    ].join('\n'),
  },
  {
    id: '15-dedale-de-nuit',
    name: "Dédale de nuit",
    hint: "L'ordre des poussées décide de tout.",
    par: 18,
    map: [
      "##########",
      "#@$    . #",
      "# ## $## #",
      "#.     $ #",
      "# ##  ## #",
      "#.       #",
      "##########",
    ].join('\n'),
  },
  {
    id: '16-grand-hall',
    name: "Grand hall",
    hint: "De la place, donc plus de façons de se tromper.",
    par: 20,
    map: [
      "##########",
      "#   ##+  #",
      "#    $   #",
      "##$$##  ##",
      "#    .  .#",
      "#   ##   #",
      "##########",
    ].join('\n'),
  },
  {
    id: '17-les-plots',
    name: "Les plots",
    hint: "Se faufiler entre les colonnes.",
    par: 21,
    map: [
      "##########",
      "#+       #",
      "#  #  #  #",
      "#.     $ #",
      "#. # $#$ #",
      "#        #",
      "##########",
    ].join('\n'),
  },
  {
    id: '18-quai-large',
    name: "Quai large",
    hint: "Aucun obstacle. Sauf les caisses elles-mêmes.",
    par: 19,
    map: [
      "##########",
      "#+.  $ $ #",
      "#       .#",
      "# $$     #",
      "#    .   #",
      "##########",
    ].join('\n'),
  },
  {
    id: '19-contre-allee',
    name: "Contre-allée",
    hint: "Un passage de plus qu'il n'en faut.",
    par: 20,
    map: [
      "##########",
      "#@       #",
      "#$##$$## #",
      "#.$      #",
      "# ##  ## #",
      "#.     ..#",
      "##########",
    ].join('\n'),
  },
  {
    id: '20-dernier-quai',
    name: "Dernier quai",
    hint: "Tout ce que le dépôt vous a appris.",
    par: 23,
    map: [
      "##########",
      "#+     $ #",
      "# ##$ ## #",
      "# $    $ #",
      "# ##  ## #",
      "# .   .. #",
      "##########",
    ].join('\n'),
  },
];

if (typeof module !== 'undefined') module.exports = { LEVELS };
